version: '3.8'

services:
  ms-catalog:
    build:
      context: ./ms-catalog
    container_name: ms-catalog
    ports:
      - "4000:4000"
    env_file:
      - ./ms-catalog/.env
    depends_on:
      - db
    networks:
      - app-net

  ms-compras:
    build:
      context: ./ms-compras
    container_name: ms-compras
    ports:
      - "4001:4001"
    env_file:
      - ./ms-compras/.env
    depends_on:
      - db
    networks:
      - app-net

  ms-inventario:
    build:
      context: ./ms-inventario
    container_name: ms-inventario
    ports:
      - "4002:4002"
    env_file:
      - ./ms-inventario/.env
    depends_on:
      - db
    networks:
      - app-net

  ms-payments:
    build:
      context: ./ms-payments
    container_name: ms-payments
    ports:
      - "4003:4003"
    env_file:
      - ./ms-payments/.env
    depends_on:
      - db
    networks:
      - app-net

  orchestrator:
    build:
      context: ./orchestrator
    container_name: orchestrator
    ports:
      - "4004:4004"
    env_file:
      - ./orchestrator/.env
    depends_on:
      - db
    networks:
      - app-net

  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: microservicios_new
    ports:
      - "5433:5432"
    networks:
      - app-net
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  app-net:
    driver: bridge

volumes:
  postgres_data: